version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - EXPCON_DATABASE_USER=test
      - EXPCON_DATABASE_PASSWORD=test
      - EXPCON_DATABASE_URL=jdbc:postgresql://db:5432/test_db

  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db

