spring:
  jpa:
    hibernate:
      dialect: whatever

ec:
  database:
    url: jdbc:postgres://10.27.12.98:5432/expense_control_config_test
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver



server:
  contextPath: /