/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'conference' at '4/30/17 10:52 PM' with Gradle 3.2
 *
 * @author conference, @date 4/30/17 10:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
